version: '3'
services:
  geyser:
    image: ghcr.io/kiyonetcat/docker-geyser:latest
    # build: .
    container_name: geyser
    environment:
      EXTENSIONS: |
        https://example.com

      RESOURCE_PACKS: |
        https://example.com

      JVM_OPTS: ""
    ports:
      - 19132:19132/udp
    restart: unless-stopped
    volumes:
      - ./data:/data
